"""``dsail init``: seed a repository so every future agent session finds DSAIL.

Both coding-agent ecosystems read repo-level instructions, and committed skills
travel with ``git clone``. So one adopting developer running this once seeds
every later session of every teammate in the repo. Every file is idempotent:

``.claude/skills/dsail/SKILL.md`` and ``.agents/skills/dsail/SKILL.md``
    The authoring sequence, grammar and integrity rule — the same text the
    hosted MCP server sends as its ``instructions`` — as a skill, once at the
    path Claude Code reads and once at the path Codex reads. Same bytes.
``.mcp.json``
    A ``dsail`` entry under ``mcpServers`` that launches ``dsail mcp``. Other
    entries in an existing file are preserved. Claude Code reads this file.
``.codex/config.toml``
    A marked ``[mcp_servers.dsail]`` table launching the same proxy. Codex CLI,
    the Codex IDE extension and the ChatGPT desktop app share one MCP
    configuration, so this registers DSAIL once for all three; a project-level
    file applies to a trusted project. Text outside the markers is untouched.
``CLAUDE.md`` and ``AGENTS.md``
    A marked stanza between ``<!-- dsail:start -->`` and ``<!-- dsail:end -->``
    pointing at the skill, the CLI and the Python client. Re-running replaces
    the stanza in place and touches nothing outside the markers. The stanza is
    written for the environment with no MCP layer at all — a Codex cloud task —
    because there the agent has no tool list to notice DSAIL in, and this text
    is the whole of its discovery.

``dsail codex-plugin`` (:func:`codex_plugin`) builds the Codex plugin bundle
from the same pieces: one installable carrying the skill, the MCP server entry
and, when an app id is supplied, the ChatGPT connector.

Everything written is derived from the bundled contract, so a newer package
re-run over an older scaffold brings the repo's instructions up to date.
"""

import json
import os

from dsail import contract
from dsail._version import __version__

START = "<!-- dsail:start -->"
END = "<!-- dsail:end -->"

TOML_START = "# dsail:start"
TOML_END = "# dsail:end"

SKILL_RELATIVE = os.path.join(".claude", "skills", "dsail", "SKILL.md")
CODEX_SKILL_RELATIVE = os.path.join(".agents", "skills", "dsail", "SKILL.md")
MCP_JSON = ".mcp.json"
CODEX_CONFIG = os.path.join(".codex", "config.toml")
STANZA_FILES = ("CLAUDE.md", "AGENTS.md")

_SKILL_TEMPLATE = """---
name: dsail
description: {skill_description}
---

# DSAIL: policy to formal ruleset, with reproducible results

{preamble}

Documentation for agents, every page as markdown: {docs_url} (`{docs_url}/llms.txt`
lists them all). Every structured error the service returns carries `docs`, the
URL of the page that resolves it — fetch it before retrying blind.

## How to work in this repository

- Rules live in the repo. Write the English policy summary and the DSAIL source
  as files next to the code they govern (for example `policies/<name>.md` and
  `policies/<name>.dsail`), commit them, and review them like code.
- The hosted service compiles and checks; nothing formal runs locally. Use the
  `dsail_*` MCP tools if they are connected, otherwise the CLI:

      dsail compile policies/<name>.dsail          # hash, manifest, review text
      dsail prompt-pack --hash <ruleset_hash>       # the extraction contract
      dsail check --hash <ruleset_hash> --claims claims.json
      dsail serve policies/<name>.dsail             # review UI at a localhost link

- No `dsail_*` tools in this session (a cloud coding task, for one, has
  no MCP layer at all) means the CLI and the Python client ARE the path, not a
  fallback: the same operations, the same service, the same results. If
  `dsail` is not installed, `pip install dsail` first.
{review_guidance}
- Integration code fetches the prompt pack, runs extraction on this project's
  own model and credentials, submits the claim dictionary with `dsail.Client`
  (`check_with_repair` handles validation failures), and acts on the
  per-assertion results. Jaxon never sees documents, keys or model choices.
- If a call fails saying outbound network access is blocked, relay that
  message to the user verbatim: it names the one-time fix for this environment.

{authoring_sequence}

{grammar_guide}

Integrity rule: {integrity_rule}

<!-- generated by dsail {version}; wire contract {wire_version}; re-run `dsail init` to refresh -->
"""

_STANZA_TEMPLATE = """{start}
## DSAIL (policy verification)

This repository uses DSAIL to turn written policies into formal rulesets and to
check extracted claim values against them on the hosted service. Before
writing or changing any policy rule, read the skill at `{codex_skill}`
(the same text is at `{claude_skill}`) and follow its authoring
sequence: English summary first, explicit confirmation, then DSAIL source,
adversarial test claims against your own draft, then a human review: call the
`dsail_open_review` tool, or without MCP hand the user the `dsail serve <file>`
command to run in their own terminal.

Three ways to reach the service, all the same operations on the same hosted
engine:

- the `dsail` MCP server, registered in `.mcp.json` and `.codex/config.toml`
  (`dsail mcp`), when this session has MCP tools;
- the CLI: `dsail compile|check|prompt-pack|serve`;
- the Python client `dsail.Client` (`pip install dsail`), for integration code.

If no `dsail_*` tool is listed in this session (a Codex cloud task has
no MCP layer at all), use the CLI or `dsail.Client` directly and without asking;
they are the intended path there, not a degraded one. Results are per assertion — TRUE,
FALSE, UNKNOWN or AMBIGUOUS — and there is no overall verdict to report or
invent. A message saying outbound network access is blocked names the one-time
fix for this environment; relay it verbatim.

Saved rulesets belong to a workspace: the user's own, plus one per TEAM they
are in. `dsail workspaces` says where they are working; `dsail use <team>`
moves. If a colleague cannot see a ruleset, the answer is a team — `dsail team
create`, then `dsail team invite <team-id> <email>`, which returns a single-use
link the user passes on themselves. A team starts empty, and `dsail copy <name>
--to <team>` is how work gets into one. Anything about who is IN a team needs a
signed-in person rather than a stored credential: if a call is refused for that
reason it names `dsail login`, which is one browser round trip and leaves the
API key alone. Tell the user to run it rather than working around it.
{end}
"""

_TOML_TEMPLATE = """{start}
# DSAIL: the stdio MCP proxy (`dsail mcp`) forwarding to the hosted service.
# Written by `dsail init`; re-run it to refresh. Codex CLI, the IDE extension
# and the ChatGPT desktop app read this one configuration.
[mcp_servers.dsail]
command = "dsail"
args = ["mcp"]
{env}{end}
"""

_PREAMBLE = (
    "DSAIL turns a written policy into a formal ruleset and returns deterministic, "
    "reproducible results over claim values you extract: given these claim values "
    "under this ruleset, every assertion answers TRUE, FALSE, UNKNOWN or AMBIGUOUS — "
    "every time, and every result names the rule that decided. Whether the claim "
    "values faithfully describe the document is your extraction's responsibility. "
    "The service never calls a language model; you run extraction on the user's own "
    "model using the prompt pack it generates. Report results in those four words, "
    "attributed to the rules, and never as an overall verdict of your own."
)

# How review reaches a person. `dsail init` registers the stdio proxy, which is
# the one process that can start the review UI on the user's machine, so its
# skill sends every review there.
_INIT_REVIEW = """- Review is a human step, and this client renders no widget. When a ruleset is
  ready, call the `dsail_open_review` MCP tool (source, file path, or stored
  name): it starts the review UI on this machine, opens the browser, and
  returns a link — repeat that link to the user. Without MCP tools, give the
  user the exact command `dsail serve policies/<name>.dsail` to run in their
  own terminal; do not run it from a sandboxed shell, and never say a review
  panel is open unless you have a link to show. Approval there is recorded on
  the service against the exact hash."""

# The plugin's Claude manifest connects to the hosted MCP endpoint (see
# claude_mcp_servers), which has no `dsail_open_review`: only a process on the
# user's machine can open their browser. claude.ai and Claude Desktop render
# `dsail_review` as the inline widget; Claude Code does not, so there the
# person runs `dsail serve` themselves. One skill serves both marketplaces, so
# it describes the two kinds of client rather than naming either ecosystem's.
_PLUGIN_REVIEW = """- Review is a human step. If `dsail_open_review` is in your tool list (the
  local `dsail mcp` proxy), call it with the source, file path or stored name:
  it starts the review UI on this machine, opens the browser and returns a
  link — repeat that link to the user. If it is not (the hosted server), call
  `dsail_review` once after a successful compile: a client that renders it
  shows an inline review widget. A client that renders no widget gets text
  only; say so, and give the user the exact command
  `dsail serve policies/<name>.dsail` to run in their own terminal (after
  `pip install dsail`). Never say a review panel is open unless one rendered or
  a link came back. Approval is recorded on the service against the exact
  hash."""

# ------------------------------------------------------------- the Codex plugin

PLUGIN_NAME = "dsail"
PLUGIN_MANIFEST_RELATIVE = os.path.join(".codex-plugin", "plugin.json")
PLUGIN_MARKETPLACE_RELATIVE = os.path.join(".agents", "plugins", "marketplace.json")
# The Claude Code half of the same plugin directory (TJP-624): a marketplace
# manifest at the repository root and a plugin manifest beside Codex's. One
# plugin directory serves both ecosystems: the skills and the README are the
# same bytes for both and name neither ecosystem's clients, because each
# marketplace shows them on its listing; only the manifest each reads differs.
CLAUDE_PLUGIN_MANIFEST_RELATIVE = os.path.join(".claude-plugin", "plugin.json")
CLAUDE_MARKETPLACE_RELATIVE = os.path.join(".claude-plugin", "marketplace.json")
MARKETPLACE_NAME = "jaxon"
PUBLIC_REPOSITORY = "https://github.com/JaxonAI/dsail"
# The product page people land on from a listing; the docs site is for agents
# and carries the documentation, support and legal links.
PRODUCT_URL = "https://jaxon.ai/dsail/"
SUPPORT_PAGE = "support.md"
_KEYWORDS = ["dsail", "policy", "rules", "verification", "mcp"]
CLAUDE_PLUGIN_KEYWORDS = _KEYWORDS + ["claude-code"]
CODEX_PLUGIN_KEYWORDS = _KEYWORDS + ["codex"]
_AUTHOR = {"name": "Jaxon, Inc.", "email": "info@jaxon.ai", "url": "https://jaxon.ai/"}

# The hosted MCP door: the service's base URL plus this path (the registry
# entry's `remotes` names the same URL).
MCP_PATH = "/mcp"

_PLUGIN_README_TEMPLATE = """# DSAIL plugin

{directory_description}

{lead}

The plugin carries the DSAIL skills (the authoring sequence and grammar, and
two guides to the policy families it is most often used for) and the `dsail`
MCP server. The server is the hosted DSAIL service at {mcp_url}, which asks you
to sign in with Google or GitHub on first use. A client that runs local
servers launches the `dsail mcp` proxy from the `dsail` Python package instead,
which forwards to the same service over HTTPS. The service receives the policy
you compile, the values you check against it and the rulesets and approvals you
save; your documents stay with your own model, which does the extraction.

Setup for each client is in the quickstarts at {docs_url}, where every page is
also served as markdown for agents.

<!-- generated by dsail {version}; wire contract {wire_version}; re-run `dsail plugin-bundle` to refresh -->
"""

# The two domain skills the directory listing names (TJP-624). Each one's name
# and description are quoted from phrasing.json's `directory_listing`; the
# bodies are how that family of written rules maps onto DSAIL. Both example
# rulesets compiled against the hosted service on 2026-10-04.
_DOMAIN_SKILL_TEMPLATE = """---
name: {name}
description: {description}
---

{body}
<!-- generated by dsail {version}; wire contract {wire_version}; re-run `dsail plugin-bundle` to refresh -->
"""

_DOMAIN_SKILL_BODIES = {
    "dsail-regulated-industry-rules": """# Regulated-industry rules with DSAIL

The written rules a regulated firm applies one case at a time: a compliance
manual, a FINRA rulebook, a suitability standard, underwriting or claims
guidelines, insurance policy wording, clinical criteria, a fee schedule, treaty
terms. DSAIL turns them into a ruleset whose every result names the rule that
decided, so the same facts get the same answer whoever is on the desk, and the
basis for a decision can be shown to an examiner later.

The `dsail` skill has the authoring sequence, the grammar and the integrity
rule. Follow it. This skill is about how these policies map onto it.

## Before writing any DSAIL

- Restate the policy in plain English, rule by rule, and get the person's
  confirmation. Name the manual section for each rule; it goes into the rule's
  description comment, so the review and every result carry it.
- DSAIL applies rules that are already written. Where the manual leaves a case
  to judgement (a "reasonable" standard, an exception a supervisor may grant),
  say so and leave that decision with the person. Do not invent a threshold.

## How these rules usually look

- **Caps and thresholds in money**: gift limits, fee breakpoints, deductibles,
  surveillance thresholds. Declare the unit on the claim (`// @unit giftValue
  USD`) and write it on every literal (`giftValue <= 100 "USD"`).
- **Limits that depend on a category**: the recipient type, the account tier,
  the coverage line, the territory. Declare the category as an enum and branch
  with `CASE` or `IF`.
- **Ordered tiers** such as risk ratings: an ordered enum
  (`["low","medium","high"]`) compares with `<` and `>`.
- **"At least N of the following"** (medical necessity, referral triggers,
  enhanced due diligence): one boolean per criterion, counted with `If`.
- **Running totals and look-backs** (gifts to the same recipient this calendar
  year, trades in the last thirty days): DSAIL checks one case's claims and does
  not aggregate history. Make the total a claim your system computes from its
  records, and write the rule against the sum.
- **One assert per written rule**, so a FALSE names the rule that blocked it.

## Example

```
version 1.3;
// @ask recipientType Who would receive the gift: a public official, a client, or a prospect the firm is pitching?
declare recipientType as enum {"public_official","client","prospect"};
// @ask giftValue What is the value of the proposed gift, in USD?
// @unit giftValue USD
// @range giftValue 0..1000000
declare giftValue as numeric;
// @ask priorGiftsThisYear What is the total value of gifts already given to this recipient this calendar year, in USD?
// @unit priorGiftsThisYear USD
// @range priorGiftsThisYear 0..1000000
declare priorGiftsThisYear as numeric;
// @ask meetsCriterionA Does the record show the first clinical criterion is met?
declare meetsCriterionA as boolean;
// @ask meetsCriterionB Does the record show the second clinical criterion is met?
declare meetsCriterionB as boolean;
// @ask meetsCriterionC Does the record show the third clinical criterion is met?
declare meetsCriterionC as boolean;

// Manual 4.1: no gift of any value to a public official.
assert no_gifts_to_officials { recipientType != "public_official" };
// Manual 4.2: gifts to one recipient may not exceed 100 USD in a calendar year.
assert annual_gift_cap { priorGiftsThisYear + giftValue <= 100 "USD" };
// Guideline 7: at least two of the three clinical criteria are met.
assert two_of_three_criteria { If(meetsCriterionA, 1, 0) + If(meetsCriterionB, 1, 0) + If(meetsCriterionC, 1, 0) >= 2 };
```

The section numbers and amounts are illustrative; use the policy's own.

## Checking, and keeping the record

- Extract claim values with the prompt pack on the user's own model. A fact the
  file does not state is "unknown", never a guess.
- Save the ruleset under a name and record the accountable person's approval
  against its hash. A later edit is a new revision and needs its own approval.
  The hash, the claim dictionary and the results are the record of what was
  decided, under which rules, on which facts.

## Not this skill

Routing a request to an approver or deciding who may act, scoring or ranking
risk where no written rule says how, judgements the policy leaves to a person,
and drafting or interpreting the policy itself.
""",
    "dsail-regulations-and-engineering-standards": """# Regulations and engineering standards with DSAIL

Written regulations and internal standards applied one case at a time: a
subcontract against FAR and DFARS flowdown clauses, a firm against NAICS size
standards, a records request against FOIA exemptions, a document against a
classification guide, a clearance case against adjudication guidelines, a
voucher against per diem rates, an incident against a severity matrix, a change
or a release against a written standard. DSAIL turns the written conditions
into a ruleset and names, for every case, the provision or requirement that
decided.

The `dsail` skill has the authoring sequence, the grammar and the integrity
rule. Follow it. This skill is about how these rules map onto it.

## Before writing any DSAIL

- Restate each provision in plain English with its citation (clause number,
  section, matrix row) and get the person's confirmation. The citation goes into
  the rule's description comment.
- DSAIL applies what the text states. Where a regulation or standard leaves the
  decision to an official (a whole-person judgement, a waiver, an "as
  appropriate"), that part stays with them.

## How these rules usually look

- **Clause flowdown**: the subcontract's attributes are claims (value in USD,
  contract type as an enum, commercial item as a boolean), plus one boolean per
  clause present. One assert per clause, so a FALSE names the missing clause.
- **Size standards and thresholds by code**: declare the code as an unordered
  enum of the codes the policy lists and branch with `CASE`; receipts carry a
  unit, headcount is a plain number.
- **Exemptions and release decisions**: one boolean per exemption, answered by
  extraction and "unknown" where the record is not clear. DSAIL applies what
  the rule says follows; it does not judge whether a passage is sensitive.
- **Classification and severity levels**: an ordered enum compares the level
  applied with the level the guide or matrix requires.
- **Rates and entitlements**: the rate for the place and dates is a claim (or
  the policy's own table, written as a `CASE`); compare the amount claimed with
  units on every literal.
- **Engineering standards** (release, change freeze, on-call, reliability
  policy, licence policy): the facts come from the change record, the incident,
  the dependency list or the release ticket, and each written requirement is
  one assert. DSAIL does not scan code, read configuration or compute figures
  such as an error budget; the system that has the facts supplies them.

## Example

```
version 1.3;
// @ask touchesPaymentPaths Does the change touch payment code paths?
declare touchesPaymentPaths as boolean;
// @ask approverCount How many people approved the release?
// @range approverCount 0..50
declare approverCount as numeric;
// @ask paymentsApprover Is at least one approver from the payments team?
declare paymentsApprover as boolean;
// @ask rollbackTested Has the rollback plan been tested?
declare rollbackTested as boolean;
// @ask subcontractValue What is the total value of the subcontract, in USD?
// @unit subcontractValue USD
// @range subcontractValue 0..10000000000
declare subcontractValue as numeric;
// @ask includesSmallBusinessPlanClause Does the subcontract include the small business subcontracting plan clause?
declare includesSmallBusinessPlanClause as boolean;
// @ask requiredLevel What classification level does the guide require for this content: unclassified, confidential, secret or top secret?
declare requiredLevel as enum ["unclassified","confidential","secret","top_secret"];
// @ask markedLevel What classification level is the document marked at: unclassified, confidential, secret or top secret?
declare markedLevel as enum ["unclassified","confidential","secret","top_secret"];

// Standard 2.1: every release needs at least one approver.
assert has_approver { approverCount >= 1 };
// Standard 3.1: a change to payment paths needs a second approver, and one from payments.
assert payments_second_approver { IF touchesPaymentPaths THEN And(approverCount >= 2, paymentsApprover) ELSE True END };
// Standard 3.2: a change to payment paths needs a tested rollback plan.
assert payments_rollback_tested { Implies(touchesPaymentPaths, rollbackTested) };
// Flowdown 4: a subcontract over 750,000 USD must carry the small business subcontracting plan clause.
assert small_business_plan_flowdown { IF subcontractValue > 750000 "USD" THEN includesSmallBusinessPlanClause ELSE True END };
// Guide 1.3: a document is marked at least at the level the guide requires for its content.
assert marked_at_required_level { markedLevel >= requiredLevel };
```

The section numbers and amounts are illustrative; use the regulation's or the
standard's own.

## Checking, and keeping the record

- Extract claim values with the prompt pack on the user's own model; a fact the
  record does not state is "unknown", never a guess.
- Save the ruleset and record the accountable person's approval against its
  hash; a later edit is a new revision and needs its own approval.

## Not this skill

Deciding who may deploy, access or approve (that is access control), scanning
code or configuration, computing figures, and interpreting an ambiguous
regulation or drafting the standard.
""",
}


def skill_description():
    """The skill's one-line description: the agreed lead, then when to reach for it.

    The lead is quoted from the bundled phrasing file rather than typed here,
    so it cannot drift from the MCP server's own description of itself — a
    coding agent choosing between skills reads this line the way a chat client
    reads a tool description.
    """
    return (
        "%s Use when asked to enforce, check or encode a policy, rule, threshold or "
        "compliance requirement against facts extracted from documents; the check runs "
        "on the hosted DSAIL service with no model in the loop."
        % contract.phrasing()["lead"]
    )


def _frontmatter_scalar(text):
    """``text`` as a YAML frontmatter value: as written when it reads as a
    plain scalar, else double-quoted. A ``: `` or `` #`` inside a plain value
    breaks the frontmatter, and the directory listing's descriptions carry
    colons. A JSON string is a valid YAML double-quoted scalar."""
    if ": " in text or " #" in text or text.endswith(":") or text[:1] in "!&*-?{}[]|>'\"%@`,#":
        return json.dumps(text, ensure_ascii=False)
    return text


def skill_markdown(description=None, review=None):
    """The skill file. ``dsail init`` writes the default; the plugin bundle
    passes the directory listing's description and the review guidance for a
    client connected to the hosted server (:func:`plugin_skill_markdown`)."""
    authoring = contract.authoring()
    return _SKILL_TEMPLATE.format(
        skill_description=_frontmatter_scalar(description or skill_description()),
        review_guidance=review or _INIT_REVIEW,
        docs_url=contract.docs_url(),
        preamble=_PREAMBLE,
        authoring_sequence=authoring["authoring_sequence"].rstrip(),
        grammar_guide=authoring["grammar_guide"].rstrip(),
        integrity_rule=authoring["integrity_rule"].strip(),
        version=__version__,
        wire_version=contract.versions().get("wire_version", "?"),
    )


def directory_listing():
    """The Claude plugin's listing in Anthropic's directory (TJP-624).

    Quoted from the bundled phrasing file: ``display_name``, ``description``,
    ``skill_description`` and ``domain_skills``. Only the Claude manifest, its
    marketplace entry and the plugin's skills use it; every other surface keeps
    the lead. phrasing.json's ``_about_directory_listing`` says why it reads as
    it does.
    """
    return contract.phrasing()["directory_listing"]


def remote_mcp_url(url=None):
    """The hosted MCP door: ``url`` (a pinned service) or the API URL, plus ``/mcp``."""
    return (url or contract.phrasing()["api_url"]).rstrip("/") + MCP_PATH


def claude_mcp_servers(url=None):
    """The Claude manifest's server: the hosted endpoint, by the proxy's name.

    claude.ai ignores a plugin's local (stdio) servers, so a plugin added from
    the directory needs a remote one. Claude Code loads the plugin's
    ``.mcp.json`` first and then the manifest's declarations, a later name
    replacing an earlier one, so declaring ``dsail`` here replaces the stdio
    proxy for Claude while Codex, which reads only ``.mcp.json``, keeps it.
    """
    return {PLUGIN_NAME: {"type": "http", "url": remote_mcp_url(url)}}


def plugin_skill_markdown():
    """The plugin's main skill: the ``dsail init`` skill with the directory
    listing's description and review guidance for the hosted server."""
    return skill_markdown(description=directory_listing()["skill_description"], review=_PLUGIN_REVIEW)


def domain_skill_markdown(skill):
    """One of the listing's domain skills, ``{"name", "description"}``."""
    return _DOMAIN_SKILL_TEMPLATE.format(
        name=skill["name"],
        description=_frontmatter_scalar(skill["description"]),
        body=_DOMAIN_SKILL_BODIES[skill["name"]].rstrip() + "\n",
        version=__version__,
        wire_version=contract.versions().get("wire_version", "?"),
    )


def stanza():
    return _STANZA_TEMPLATE.format(
        start=START,
        end=END,
        codex_skill=CODEX_SKILL_RELATIVE.replace(os.sep, "/"),
        claude_skill=SKILL_RELATIVE.replace(os.sep, "/"),
    )


def mcp_entry(url=None, credential_env=None):
    """The ``mcpServers`` entry. ``url`` pins a non-default service."""
    entry = {"command": "dsail", "args": ["mcp"]}
    env = {}
    if url:
        env["DSAIL_URL"] = url
    if env:
        entry["env"] = env
    return entry


def codex_toml_block(url=None):
    """The marked ``[mcp_servers.dsail]`` table for ``.codex/config.toml``."""
    env = ""
    if url:
        env = "env = { DSAIL_URL = %s }\n" % json.dumps(url)
    return _TOML_TEMPLATE.format(start=TOML_START, end=TOML_END, env=env)


def _write_if_changed(path, text):
    current = None
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as handle:
            current = handle.read()
    if current == text:
        return "unchanged"
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    return "created" if current is None else "updated"


def _read_if_present(path):
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as handle:
            return handle.read()
    return None


def upsert_marked(existing, block, start, end):
    """``existing`` with the block between ``start``/``end`` replaced, appended, or created."""
    if existing is None or not existing.strip():
        return block
    first = existing.find(start)
    last = existing.find(end)
    if first != -1 and last != -1 and last > first:
        last += len(end)
        return existing[:first] + block.rstrip("\n") + existing[last:]
    separator = "" if existing.endswith("\n\n") else ("\n" if existing.endswith("\n") else "\n\n")
    return existing + separator + block


def upsert_stanza(existing, block):
    """``existing`` with the marked stanza replaced, appended, or created."""
    return upsert_marked(existing, block, START, END)


def merge_mcp_json(existing_text, entry):
    """The ``.mcp.json`` content with ``mcpServers.dsail`` set, all else kept."""
    document = {}
    if existing_text and existing_text.strip():
        document = json.loads(existing_text)
        if not isinstance(document, dict):
            raise ValueError(".mcp.json must hold a JSON object")
    servers = document.get("mcpServers")
    if not isinstance(servers, dict):
        servers = {}
    servers["dsail"] = entry
    document["mcpServers"] = servers
    return json.dumps(document, indent=2) + "\n"


def init(root, url=None, write_skill=True, write_mcp=True, write_codex=True,
         stanza_files=STANZA_FILES):
    """Scaffold ``root``. Returns ``{relative path: created|updated|unchanged}``."""
    outcomes = {}
    if write_skill:
        skill = skill_markdown()
        outcomes[SKILL_RELATIVE] = _write_if_changed(os.path.join(root, SKILL_RELATIVE), skill)
        if write_codex:
            outcomes[CODEX_SKILL_RELATIVE] = _write_if_changed(
                os.path.join(root, CODEX_SKILL_RELATIVE), skill
            )
    if write_mcp:
        path = os.path.join(root, MCP_JSON)
        outcomes[MCP_JSON] = _write_if_changed(
            path, merge_mcp_json(_read_if_present(path), mcp_entry(url))
        )
        if write_codex:
            path = os.path.join(root, CODEX_CONFIG)
            outcomes[CODEX_CONFIG] = _write_if_changed(
                path,
                upsert_marked(_read_if_present(path), codex_toml_block(url), TOML_START, TOML_END),
            )
    block = stanza()
    for name in stanza_files:
        path = os.path.join(root, name)
        outcomes[name] = _write_if_changed(path, upsert_stanza(_read_if_present(path), block))
    return outcomes


# ------------------------------------------------------------- the Codex plugin


def plugin_manifest(app_id=None):
    """``.codex-plugin/plugin.json``: the shape the Codex plugin marketplace publishes.

    ``skills``, ``mcpServers`` and ``apps`` are paths relative to the plugin
    root; ``apps`` is present only when a ChatGPT app id was supplied, because
    the id is assigned by OpenAI when the connector is registered and cannot be
    derived here.
    """
    phrasing = contract.phrasing()
    docs_url = contract.docs_url()
    manifest = {
        "name": PLUGIN_NAME,
        "version": __version__,
        "description": phrasing["lead"],
        "author": dict(_AUTHOR),
        "homepage": docs_url,
        "repository": PUBLIC_REPOSITORY,
        "license": "Apache-2.0",
        "keywords": list(CODEX_PLUGIN_KEYWORDS),
        "skills": "./skills/",
        "mcpServers": "./.mcp.json",
        "interface": {
            "displayName": "DSAIL",
            "shortDescription": phrasing["lead"],
            "longDescription": (
                "%s A written policy becomes a formal ruleset; your model extracts the claim "
                "values; the hosted service returns each assertion's own result — TRUE, FALSE, "
                "UNKNOWN or AMBIGUOUS — with the rule that decided. No model in the loop: the "
                "service never calls one."
                % phrasing["lead"]
            ),
            "developerName": "Jaxon, Inc.",
            "category": "Developer Tools",
            "capabilities": ["Read", "Write"],
            "websiteURL": docs_url,
            "privacyPolicyURL": "%s/legal/privacy.md" % docs_url,
            "termsOfServiceURL": "%s/legal/terms.md" % docs_url,
            "defaultPrompt": [
                "Turn our written expense policy into rules a program can check",
                "Check these extracted values against the policy and tell me which rule decided",
            ],
            "brandColor": "#1F3A5F",
            "screenshots": [],
        },
    }
    if app_id:
        manifest["apps"] = "./.app.json"
    return manifest


def plugin_mcp_json(url=None):
    return {"mcpServers": {"dsail": mcp_entry(url)}}


def plugin_app_json(app_id):
    """``.app.json``: the bundled ChatGPT connector, by the id OpenAI assigned it."""
    return {"apps": {"dsail": {"id": app_id, "required": False}}}


def marketplace_json(plugin_relative_path):
    """A private marketplace of this one plugin, so the directory installs as-is."""
    return {
        "name": MARKETPLACE_NAME,
        "interface": {"displayName": "Jaxon"},
        "plugins": [
            {
                "name": PLUGIN_NAME,
                "source": {"source": "local", "path": plugin_relative_path},
                # Codex's marketplace schema accepts exactly ON_INSTALL or
                # ON_USE here; `codex plugin marketplace add` refused the
                # bundle with any other spelling (measured 2026-09-21).
                "policy": {"installation": "AVAILABLE", "authentication": "ON_USE"},
                "category": "Developer Tools",
            }
        ],
    }


def claude_plugin_manifest(url=None):
    """``.claude-plugin/plugin.json``: the shape Claude Code and Anthropic's directory read.

    Name, version, the docs URL and the public repository as in the Codex
    manifest; the display name and description from the directory listing,
    which is what claude.ai's ``search_plugins`` matches and what an agent reads
    in its results; and the hosted MCP server (:func:`claude_mcp_servers`).
    ``skills`` points at the same directory Codex reads. The homepage is the
    product page; the four link fields Anthropic's directory reads for the
    listing (and Claude Code ignores) point into the docs site.
    """
    listing = directory_listing()
    docs_url = contract.docs_url()
    legal = contract.phrasing()["legal"]
    return {
        "name": PLUGIN_NAME,
        "displayName": listing["display_name"],
        "version": __version__,
        "description": listing["description"],
        "author": dict(_AUTHOR),
        "homepage": PRODUCT_URL,
        "documentationUrl": docs_url,
        "supportUrl": "%s/%s" % (docs_url, SUPPORT_PAGE),
        "privacyPolicyUrl": "%s/%s" % (docs_url, legal["privacy"]),
        "termsOfServiceUrl": "%s/%s" % (docs_url, legal["terms"]),
        "repository": PUBLIC_REPOSITORY,
        "license": "Apache-2.0",
        "keywords": list(CLAUDE_PLUGIN_KEYWORDS),
        "skills": "./skills/",
        "mcpServers": claude_mcp_servers(url),
    }


def claude_marketplace_json(plugin_relative_path):
    """``.claude-plugin/marketplace.json``: a marketplace of this one plugin.

    Lives at the public repository's root, so ``/plugin marketplace add
    JaxonAI/dsail`` finds it. The plugin entry repeats the manifest's metadata
    because the marketplace listing is what a person (or ``search_plugins``)
    reads before the plugin is fetched.
    """
    phrasing = contract.phrasing()
    docs_url = contract.docs_url()
    listing = directory_listing()
    return {
        "name": MARKETPLACE_NAME,
        "owner": dict(_AUTHOR),
        "description": phrasing["lead"],
        "metadata": {"pluginRoot": "./plugins"},
        "plugins": [
            {
                "name": PLUGIN_NAME,
                "source": plugin_relative_path,
                "displayName": listing["display_name"],
                "description": listing["description"],
                "version": __version__,
                "author": dict(_AUTHOR),
                "homepage": docs_url,
                "repository": PUBLIC_REPOSITORY,
                "license": "Apache-2.0",
                "keywords": list(CLAUDE_PLUGIN_KEYWORDS),
                "category": "developer-tools",
                "tags": [
                    phrasing["trigger_phrases"]["policy_to_rules"],
                    phrasing["trigger_phrases"]["same_answer"],
                    phrasing["trigger_phrases"]["check_extracted_values"],
                ],
            }
        ],
    }


def _dump(document):
    return json.dumps(document, indent=2, sort_keys=True) + "\n"


def codex_plugin(root, url=None, app_id=None):
    """Build the plugin bundle under ``root``.

    Layout, the one the Codex marketplace repository uses::

        <root>/.agents/plugins/marketplace.json
        <root>/plugins/dsail/.codex-plugin/plugin.json
        <root>/plugins/dsail/.mcp.json
        <root>/plugins/dsail/.app.json            (only with app_id)
        <root>/plugins/dsail/skills/dsail/SKILL.md
        <root>/plugins/dsail/skills/<domain skill>/SKILL.md   (one per directory_listing domain skill)
        <root>/plugins/dsail/README.md

    Returns ``{relative path: created|updated|unchanged}``.
    """
    plugin_dir = os.path.join("plugins", PLUGIN_NAME)
    outcomes = {}

    def write(relative, text):
        outcomes[relative] = _write_if_changed(os.path.join(root, relative), text)

    write(PLUGIN_MARKETPLACE_RELATIVE, _dump(marketplace_json("./" + plugin_dir.replace(os.sep, "/"))))
    write(os.path.join(plugin_dir, PLUGIN_MANIFEST_RELATIVE), _dump(plugin_manifest(app_id)))
    write(os.path.join(plugin_dir, ".mcp.json"), _dump(plugin_mcp_json(url)))
    app_path = os.path.join(root, plugin_dir, ".app.json")
    if app_id:
        write(os.path.join(plugin_dir, ".app.json"), _dump(plugin_app_json(app_id)))
    elif os.path.exists(app_path):
        os.remove(app_path)
        outcomes[os.path.join(plugin_dir, ".app.json")] = "removed"
    write(os.path.join(plugin_dir, "skills", "dsail", "SKILL.md"), plugin_skill_markdown())
    for skill in directory_listing()["domain_skills"]:
        write(os.path.join(plugin_dir, "skills", skill["name"], "SKILL.md"), domain_skill_markdown(skill))
    write(
        os.path.join(plugin_dir, "README.md"),
        _PLUGIN_README_TEMPLATE.format(
            directory_description=directory_listing()["description"],
            mcp_url=remote_mcp_url(url),
            lead=contract.phrasing()["lead"],
            docs_url=contract.docs_url(),
            version=__version__,
            wire_version=contract.versions().get("wire_version", "?"),
        ),
    )
    return outcomes


def plugin_bundle(root, url=None, app_id=None):
    """Both marketplaces over one plugin directory (TJP-624).

    :func:`codex_plugin`'s layout plus the Claude Code half::

        <root>/.claude-plugin/marketplace.json
        <root>/plugins/dsail/.claude-plugin/plugin.json

    The public repository's root is built with this, so the one repository is a
    Claude Code marketplace and a Codex marketplace at once. A test asserts the
    committed bundle is what this function generates, so the two cannot drift.
    """
    plugin_dir = os.path.join("plugins", PLUGIN_NAME)
    outcomes = codex_plugin(root, url=url, app_id=app_id)
    outcomes[CLAUDE_MARKETPLACE_RELATIVE] = _write_if_changed(
        os.path.join(root, CLAUDE_MARKETPLACE_RELATIVE),
        _dump(claude_marketplace_json("./" + plugin_dir.replace(os.sep, "/"))),
    )
    outcomes[os.path.join(plugin_dir, CLAUDE_PLUGIN_MANIFEST_RELATIVE)] = _write_if_changed(
        os.path.join(root, plugin_dir, CLAUDE_PLUGIN_MANIFEST_RELATIVE),
        _dump(claude_plugin_manifest(url)),
    )
    return outcomes
